### ISSUE TITLE
Better error reporting needed when using the wrong kind of token

### ISSUE THREAD

**Issue by lack** [redhat-eets/glpi-helper-scripts#10]
If I use my "Personal token" instead of the "API token", I get the following message:

```
Traceback (most recent call last):
  File "/home/jramsay/src/lab/glpi-helper-scripts/filtering/./check_glpi_reservation.py", line 91, in <module>
    main()
  File "/home/jramsay/src/lab/glpi-helper-scripts/filtering/./check_glpi_reservation.py", line 78, in main
    session_object = SessionHandler(user_token, urls.INIT_URL, urls.KILL_URL, no_verify)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jramsay/src/lab/glpi-helper-scripts/filtering/../common/sessionhandler.py", line 45, in __init__
    {"Session-Token": self.session_token.json()["session_token"]}
                      ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

It should tell me that I'm using the wrong token.

**Comment by dkosteck** [comment]
This is more verbose via https://github.com/redhat-eets/glpi-helper-scripts/pull/21
