### ISSUE TITLE
Better error reporting needed when user has insufficient permissions

### ISSUE THREAD

**Issue by lack** [redhat-eets/glpi-helper-scripts#11]
My user does not have permissions to view the reservations. When I try, I get the following backtrace:

```
Traceback (most recent call last):
  File "/home/jramsay/src/lab/glpi-helper-scripts/filtering/./check_glpi_reservation.py", line 91, in <module>
    main()
  File "/home/jramsay/src/lab/glpi-helper-scripts/filtering/./check_glpi_reservation.py", line 81, in main
    print(get_reservations(session, urls))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jramsay/src/lab/glpi-helper-scripts/filtering/../common/utils.py", line 1254, in get_reservations
    + user_json["name"]
      ~~~~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

This should probably tell me what went wrong in a clearer way.

**Comment by dkosteck** [comment]
More verbose via https://github.com/redhat-eets/glpi-helper-scripts/pull/21
