### ISSUE TITLE
Better support Quanta servers in create_glpi_computer_redfish.py

### ISSUE THREAD

**Issue by Gelob** [redhat-eets/glpi-helper-scripts#83]
### Issue 1

Running create_glpi_computer_redfish.py against a QuantaGrid D54Q-2U server resulted in the following error:
```
Getting Redfish system URI:
Getting Redfish system information:
Getting Redfish processor information:
Getting Redfish memory information:
Getting Redfish storage information:
Getting Redfish system information:
Getting Redfish network information:
Traceback (most recent call last):
  File "/Users/rgelobte/Desktop/glpi-helper-scripts/population/./create_glpi_computer_redfish.py", line 1267, in <module>
    main()
  File "/Users/rgelobte/Desktop/glpi-helper-scripts/population/./create_glpi_computer_redfish.py", line 210, in main
    nic_list, port_list = get_network(REDFISH_OBJ)
  File "/Users/rgelobte/Desktop/glpi-helper-scripts/population/./create_glpi_computer_redfish.py", line 439, in get_network
    for port in ports_info.dict.get("Members", []):
UnboundLocalError: local variable 'ports_info' referenced before assignment
```

This is because in the nic_info variable Quanta refers to NetworkPorts as Ports. Could we create a use case for this where we check for NetworkPorts or Ports?.

Also instead of throwing an error if network_ports is None, could we print a message stating that the Network Ports could not be enumerated and will be skipped from import?

This is the contents of nic_info

```
{"@odata.context":"/redfish/v1/$metadata#NetworkAdapter.NetworkAdapter","@odata.etag":"\"1697200285\"","@odata.id":"/redfish/v1/Chassis/Self/NetworkAdapters/DevType7_NIC0","@odata.type":"#NetworkAdapter.v1_5_0.NetworkAdapter","Controllers":[{"FirmwarePackageVersion":"43.f7.00.00","Links":{"NetworkDeviceFunctions":[{"@odata.id":"/redfish/v1/Chassis/Self/NetworkAdapters/DevType7_NIC0/NetworkDeviceFunctions/NetworkDeviceFunction0"}],"NetworkDeviceFunctions@odata.count":1,"PCIeDevices":[{"@odata.id":"/redfish/v1/Chassis/Self/PCIeDevices/00_16_00"}],"PCIeDevices@odata.count":1,"Ports":[{"@odata.id":"/redfish/v1/Chassis/Self/NetworkAdapters/DevType7_NIC0/Ports/DevType7_Instance0_PORT0"}],"Ports@odata.count":1}},{"FirmwarePackageVersion":"43.f7.00.00","Links":{"NetworkDeviceFunctions":[{"@odata.id":"/redfish/v1/Chassis/Self/NetworkAdapters/DevType7_NIC0/NetworkDeviceFunctions/NetworkDeviceFunction1"}],"NetworkDeviceFunctions@odata.count":1,"PCIeDevices":[{"@odata.id":"/redfish/v1/Chassis/Self/PCIeDevices/00_16_00"}],"PCIeDevices@odata.count":1,"Ports":[{"@odata.id":"/redfish/v1/Chassis/Self/NetworkAdapters/DevType7_NIC0/Ports/DevType7_Instance1_PORT1"}],"Ports@odata.count":1}}],"Id":"DevType7_NIC0","Name":"DevType7_NIC0","NetworkDeviceFunctions":{"@odata.id":"/redfish/v1/Chassis/Self/NetworkAdapters/DevType7_NIC0/NetworkDeviceFunctions"},"Ports":{"@odata.id":"/redfish/v1/Chassis/Self/NetworkAdapters/DevType7_NIC0/Ports"},"Status":{"Health":"OK","State":"Disabled"}}
```

As a test I replaced lines 430, 435, 441 with Ports instead of NetworkPorts and the script executed without issue.

### Issue 2
This specific server is a loaner and the SerialNumber field is blank `"SerialNumber": "",`. The SKU field however is not blank although it isn't a unique. `"SKU": "QuantaGrid D54Q-2U_S6Q PANEL BD FRONT"`. Ideally, the script should error out if SerialNumber is blank (and --sku isnt specified) and require the user to manual specify the hostname (new option?). Otherwise GLPI will keep adding data and overwriting existing data on any Computer which does not have a SerialNumber.

**Comment by Gelob** [comment]
### Issue 3.

--sku is only supported if the system manufacturer is Dell. It would be nice to be able to use this option if the manufacturer is not Dell. I understand those system may not have the SKU in system_json so we should account for that or let it normal to throw an error if the user is specifically specifying --sku and one does not exist.
